micronaut:
  application:
    name: demo
datasources:
  default:
    url: 'jdbc:h2:mem:testDb;DATABASE_TO_UPPER=false'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver
    dialect: H2
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:flyway